
project_id = "ifxvwettmgixfbivlzzl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://preview--whats-app-sends-15.lovable.app"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false

[functions.whapi-simple-connect]
verify_jwt = false

[functions.whapi-simple-webhook]
verify_jwt = false

[functions.whapi-simple-disconnect]
verify_jwt = false

[functions.send-immediate-message]
verify_jwt = false

[functions.sync-whatsapp-groups]
verify_jwt = false

[functions.whatsapp-scheduler]
verify_jwt = false

[functions.cleanup-expired-trials]
verify_jwt = false
