// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifxvwettmgixfbivlzzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmeHZ3ZXR0bWdpeGZiaXZsenpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzE0MDAsImV4cCI6MjA2NTQwNzQwMH0.mjmY61D9ZS3WKjpN1kgA1O0npFmXmXFHc4Q2WpyBi2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);